### ISSUE TITLE
Error in fix_issue_17(x)

### ISSUE THREAD

**Issue by GermanFernandezz** [lgatto/rpx#24] opened 2023-05-24 14:34 UTC
Hello!
I am doing the tutorial http://bioconductor.org/packages/3.10/bioc/vignettes/proteoQC/inst/doc/proteoQC.html
But i get the following error
> px <- PXDataset("PXD000864")
Querying ProteomeXchange for PXD000864.
Error in fix_issue_17(x) : Can't access URL(s):
 ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2014/03/PXD000864
 ftp://ftp.pride.ebi.ac.uk/pride-archive/2014/03/PXD000864

**Comment by lgatto** [comment] 2023-05-24 15:19
What is your `sessionInfo()`? I suspect you need to update your R/Bioc.

I works here with the latest versions of R and rpx.

```r
> library(rpx)
> px <- PXDataset("PXD000864")
Querying ProteomeXchange for PXD000864.
> px
Project PXD000864 with 218 files
 Resource ID BFC1254 in cache in /home/lgatto/.cache/R/rpx.
 [1] 'README.txt' ... [218] 'TTE2010.zip'
 Use 'pxfiles(.)' to see all files.
> sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3 
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Brussels
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rpx_2.8.0

loaded via a namespace (and not attached):
 [1] vctrs_0.6.2         httr_1.4.6          cli_3.6.1          
 [4] rlang_1.1.1         DBI_1.1.3           BiocFileCache_2.8.0
 [7] purrr_1.0.1         generics_0.1.3      jsonlite_1.8.4     
[10] glue_1.6.2          bit_4.0.5           RCurl_1.98-1.12    
[13] dbplyr_2.3.2        fansi_1.0.4         filelock_1.0.2     
[16] tibble_3.2.1        bitops_1.0-7        fastmap_1.1.1      
[19] lifecycle_1.0.3     memoise_2.0.1       BiocManager_1.30.20
[22] compiler_4.3.0      dplyr_1.1.2         RSQLite_2.3.1      
[25] blob_1.2.4          pkgconfig_2.0.3     R6_2.5.1           
[28] tidyselect_1.2.0    utf8_1.2.3          curl_5.0.0         
[31] pillar_1.9.0        magrittr_2.0.3      withr_2.5.0        
[34] tools_4.3.0         bit64_4.0.5         xml2_1.3.4         
[37] cachem_1.0.8       
```

**Comment by lgatto** [comment] 2023-05-29 17:33
Could you then try again in a new session. I checked again and I can't reproduce your error.

**Comment by lgatto** [comment] 2023-05-29 18:08
Yes. Can you open this URL in your browser

http://ftp.pride.ebi.ac.uk/pride/data/archive/2014/03/PXD000864/

**Comment by GermanFernandezz** [comment] 2023-05-29 18:13
Yes

**Comment by GermanFernandezz** [comment] 2023-05-29 20:19
Hi, ii is something with my work connection.
I will tried to solve it.
Thanks for your help.

**Comment by lgatto** [comment] 2023-05-30 05:45
Closing for now, but feel free to re-open if necessary.

**Closed by lgatto** 2023-05-30 05:45 UTC
